### PR TITLE
style: use figma.tokens.json as basis for theme

### PR DESCRIPTION
**Pull request by Robbert**
TODO: fix 60 collisions

```log
Token collisions detected (60):

Collision detected at: tilburg.feedback.informative.background-color! Original value: {tilburg.color.blue.100}, New value: {tilburg.color.blue.100}
Collision detected at: tilburg.feedback.informative.background-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.informative.background-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.informative.background-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.informative.border-color! Original value: {tilburg.color.blue.400}, New value: {tilburg.color.blue.400}
Collision detected at: tilburg.feedback.informative.border-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.informative.border-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.informative.border-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.informative.color! Original value: {tilburg.color.blue.400}, New value: {tilburg.color.blue.400}
Collision detected at: tilburg.feedback.informative.color! Original value: color, New value: color
Collision detected at: tilburg.feedback.informative.color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.informative.color! Original value: true, New value: true
Collision detected at: tilburg.feedback.negative.background-color! Original value: {tilburg.color.red.100}, New value: {tilburg.color.red.100}
Collision detected at: tilburg.feedback.negative.background-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.negative.background-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.negative.background-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.negative.border-color! Original value: {tilburg.color.red.300}, New value: {tilburg.color.red.300}
Collision detected at: tilburg.feedback.negative.border-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.negative.border-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.negative.border-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.negative.color! Original value: {tilburg.color.red.300}, New value: {tilburg.color.red.300}
Collision detected at: tilburg.feedback.negative.color! Original value: color, New value: color
Collision detected at: tilburg.feedback.negative.color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.negative.color! Original value: true, New value: true
Collision detected at: tilburg.feedback.positive.background-color! Original value: {tilburg.color.green.100}, New value: {tilburg.color.green.100}
Collision detected at: tilburg.feedback.positive.background-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.positive.background-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.positive.background-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.positive.border-color! Original value: {tilburg.color.green.300}, New value: {tilburg.color.green.300}
Collision detected at: tilburg.feedback.positive.border-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.positive.border-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.positive.border-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.positive.color! Original value: {tilburg.color.green.300}, New value: {tilburg.color.green.300}
Collision detected at: tilburg.feedback.positive.color! Original value: color, New value: color
Collision detected at: tilburg.feedback.positive.color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.positive.color! Original value: true, New value: true
Collision detected at: tilburg.feedback.warning.background-color! Original value: {tilburg.color.orange.100}, New value: {tilburg.color.orange.100}
Collision detected at: tilburg.feedback.warning.background-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.warning.background-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.warning.background-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.warning.border-color! Original value: {tilburg.color.orange.300}, New value: {tilburg.color.orange.300}
Collision detected at: tilburg.feedback.warning.border-color! Original value: color, New value: color
Collision detected at: tilburg.feedback.warning.border-color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.warning.border-color! Original value: true, New value: true
Collision detected at: tilburg.feedback.warning.color! Original value: {tilburg.color.orange.300}, New value: {tilburg.color.orange.300}
Collision detected at: tilburg.feedback.warning.color! Original value: color, New value: color
Collision detected at: tilburg.feedback.warning.color! Original value: src/common/tilburg/form-control.tokens.json, New value: src/common/tilburg/form-control.tokens.json
Collision detected at: tilburg.feedback.warning.color! Original value: true, New value: true
Collision detected at: tilburg.icon.functional.size! Original value: {tilburg.size.icon.md}, New value: {tilburg.size.icon.md}
Collision detected at: tilburg.icon.functional.size! Original value: sizing, New value: sizing
Collision detected at: tilburg.icon.functional.size! Original value: src/common/tilburg/icon.tokens.json, New value: src/common/tilburg/icon.tokens.json
Collision detected at: tilburg.icon.functional.size! Original value: true, New value: true
Collision detected at: tilburg.icon.toptask.size! Original value: {tilburg.size.icon.4xl}, New value: {tilburg.size.icon.4xl}
Collision detected at: tilburg.icon.toptask.size! Original value: sizing, New value: sizing
Collision detected at: tilburg.icon.toptask.size! Original value: src/common/tilburg/icon.tokens.json, New value: src/common/tilburg/icon.tokens.json
Collision detected at: tilburg.icon.toptask.size! Original value: true, New value: true
Collision detected at: tilburg.pointer-target.min-size! Original value: {tilburg.size.md}, New value: {tilburg.size.md}
Collision detected at: tilburg.pointer-target.min-size! Original value: sizing, New value: sizing
Collision detected at: tilburg.pointer-target.min-size! Original value: src/common/tilburg/pointer-target.tokens.json, New value: src/common/tilburg/pointer-target.tokens.json
Collision detected at: tilburg.pointer-target.min-size! Original value: true, New value: true
```

### CODE REVIEW

**Comment by hansregeer** [comment]
I have merged the other MR with the style dictionary changes, please sync this branch with latest from main.

**Comment by hansregeer** [comment]
@Robbert What would you suggest we do with this MR ? merge it and build on top of it, basically address the TODOS in the collisions? 

FYI @NickDITP

**Review by hansregeer — DISMISSED** [review]

**Comment by hansregeer** [comment]
> @Robbert What would you suggest we do with this MR ? merge it and build on top of it, basically address the TODOS in the collisions?
> 
> FYI @NickDITP

OK I read the post in slack, will let Nick follow this up

**Review by NickDITP — APPROVED** [review]
Looks good, we will fix the token collisions whilst we work on them (they still get updated often)

**Pull request merged**
